### ISSUE TITLE
Version stable ?

### ISSUE THREAD

**Issue by c4software** [FrancqNicolas/MON-tp-vuejs#1]
Bonjour,

Le projet ne comporte pas de tag je ne sais pas si la version actuel est la version stable. Est-il possible de créer un tag pour indiquer un numéro de version à ton code ?

Valentin,

**Comment by FrancqNicolas** [comment]
Bonjour,

Le tag est ajouté,
bonne journée

**Comment by c4software** [comment]
Merci ! Parfait 👍
